### ISSUE TITLE
Error : Unable to start launcher MIDlet, java.lang.NullPointerException

### ISSUE THREAD

**Issue by tumatanquang** [kitakeyos2003/JTDesktop#1]
Xin chào, mình dùng thử mã của bạn, đã import tệp `me.kitakeyos.jtd-0.0.2.jar` vào thư viện của dự án, nhưng khi run thì nó ném lỗi:
```
error Message: Error : Unable to start launcher MIDlet, java.lang.NullPointerException java.lang.NullPointerException
	  org.microemu.app.Common.startLauncher(Common.java:468)
java.lang.NullPointerException
	at org.microemu.MIDletBridge.getMIDletAccess(MIDletBridge.java:119)
	at org.microemu.app.Common.startLauncher(Common.java:465)
	at org.microemu.app.Common.startApp(Common.java:664)
	at org.microemu.app.Main.startApp(Main.java:205)
	at com.barteo.emulator.app.Application.start(Application.java:57)
	at Main.main(Main.java:10)
error Message: Error : Unable to start launcher MIDlet, java.lang.NullPointerException java.lang.NullPointerException
	  org.microemu.app.Common.startLauncher(Common.java:468)
java.lang.NullPointerException
	at org.microemu.MIDletBridge.getMIDletAccess(MIDletBridge.java:119)
	at org.microemu.app.Common.startLauncher(Common.java:465)
	at org.microemu.app.Common.initMIDlet(Common.java:1078)
	at org.microemu.app.Common.startApp(Common.java:666)
	at org.microemu.app.Main.startApp(Main.java:205)
	at com.barteo.emulator.app.Application.start(Application.java:57)
	at Main.main(Main.java:10)
```
Mã của mình:
```
import com.barteo.emulator.app.Application;
public class Main {
	public static void main(String[] args) {
		Application application = new Application("Mini Game",
								game.GameStart.class,
								(short)640,
								(short)368,
								args,
								"/icon.png");
		application.start(); // lỗi ở dòng này
	}
}
```
Không biết phải fix thế nào nhỉ?

**Comment by kitakeyos-dev** [comment]
Bạn thử bản mới nhất và setManifest cho nó
```
package me.kitakeyos;

import com.barteo.emulator.app.Application;

public class GameMain {
    public static void main(String[] args) {
        Application application = new Application("Gopet", MGOMidlet.class, (short) 500, (short) 400, "/icon.png", args);
        application.setManifest("game.ini");
        application.start();
    }
}
```

**Comment by tumatanquang** [comment]
Mình import tệp jtd-0.0.4.jar vào project, sau đó sửa lại mã như của bạn. Nhưng khi run trực tiếp thì nó lỗi:
```
Exception in thread "main" java.lang.NullPointerException
        at org.microemu.app.Common.startApp(Common.java:648)
        at org.microemu.app.Main.startApp(Main.java:205)
        at com.barteo.emulator.app.Application.start(Application.java:57)
        at game.Launch.main(Launch.java:7)
```
Sau đó mình thử tạo một tệp `game.ini` ở cùng thư mục với tệp jar, lần này nó báo lỗi:
```
error Message: Error : Unable to start launcher MIDlet, java.lang.NullPointerException java.lang.NullPointerException
          org.microemu.app.Common.startLauncher(Common.java:468)
java.lang.NullPointerException
        at org.microemu.MIDletBridge.getMIDletAccess(MIDletBridge.java:119)
        at org.microemu.app.Common.startLauncher(Common.java:465)
        at org.microemu.app.Common.startApp(Common.java:664)
        at org.microemu.app.Main.startApp(Main.java:205)
        at com.barteo.emulator.app.Application.start(Application.java:57)
        at gameLaunch.main(Launch.java:7)
error Message: Error : Unable to start launcher MIDlet, java.lang.NullPointerException java.lang.NullPointerException
          org.microemu.app.Common.startLauncher(Common.java:468)
java.lang.NullPointerException
        at org.microemu.MIDletBridge.getMIDletAccess(MIDletBridge.java:119)
        at org.microemu.app.Common.startLauncher(Common.java:465)
        at org.microemu.app.Common.initMIDlet(Common.java:1078)
        at org.microemu.app.Common.startApp(Common.java:666)
        at org.microemu.app.Main.startApp(Main.java:205)
        at com.barteo.emulator.app.Application.start(Application.java:57)
        at game.Launch.main(Launch.java:7)
```
Dòng 7 vẫn là dòng `application.start();`.

**Comment by kitakeyos-dev** [comment]
bạn có thể gửi mình file .jar của ứng dụng j2me ko

**Comment by tumatanquang** [comment]
Đây nhé: [LongTinhThanhLong.jar](https://www.mediafire.com/file/436wsten8dwv9rs/LongTinhThanhLong.jar/file)

**Comment by kitakeyos-dev** [comment]
bạn thử code như này xem nha, file game.ini là chứa nội dung file MANIFEST.MF (của game)
```
import com.barteo.emulator.app.Application;
import game.UCGameStart;

public class Main {
    public static void main(String[] args) {
        Application application = new Application("Long Tinh Tứ Tượng", UCGameStart.class, (short) 320, (short) 240, "/icon.png", args);
        application.setManifest("game.ini");
        application.start();

    }
}
```

**Comment by kitakeyos-dev** [comment]
[LongTinhThanhLongPC.jar](https://www.mediafire.com/file/5sbn1l65pzewrrt/LongTinhThanhLongPC.jar/file)

**Comment by tumatanquang** [comment]
Mình thử rồi, nó vẫn bị:
```
Exception in thread "main" java.lang.NullPointerException
        at org.microemu.app.Common.startApp(Common.java:648)
        at org.microemu.app.Main.startApp(Main.java:205)
        at com.barteo.emulator.app.Application.start(Application.java:57)
        at Main.main(Main.java:8)
```
Nó có yêu cầu gì về phiên bản Java không bạn?
